version: 2.1
orbs: 
    python: circleci/python@2.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run: 
          command: |
            pip install pytest
            cd legacy
            pytest --junitxml=test-results/junit.xml TestTriangle.py

      # For GitHub API tests
      - run:
          name: "Installing Git API Dependencies"
          command: |
            pip install pytest requests
      - run:
          name: "Run Git API Tests"
          command: |
            cd GitHubApi567-hw4a/
            pytest --junitxml=test-results-github-api/junit.xml test_git_api.py


      # Store test results
      - store_test_results:
          path: test-results-triangle
      - store_test_results:
          path: test-results-git-api

workflows:
  testing_triangles:
    jobs:
      - build-and-test
